const fakedata = [
     {
          name:'LAMBORGHINI', 
          description:'FOR SALE',
          fuel:'Petrol',
          mile:'4000',
          price:'$1050',
          type:'Sport',
          color:'Yellow',
          model:'2019',
          img:'https://i.ibb.co/8j9ZxHH/product-6.jpg'
     },
     {
          name:'FERRARI', 
          description:'FOR SALE',
          fuel:'Petrol',
          mile:'4000',
          price:'$950',
          type:'Sport',
          color:'Red',
          model:'2019',
          img:'https://i.ibb.co/w4hPmr0/product-2.jpg'
     },
     {
          name:'BMW E46 M3 DISKI SERIE', 
          description:'FOR RENT',
          fuel:'Petrol',
          mile:'8000',
          price:'$1150',
          type:'Sport',
          color:'Black',
          model:'2021',
          img:'https://i.ibb.co/MCDGHvT/product-5.jpg'
     },
     {
          name:'VOLKSWAGEN SCIROCCO 2016', 
          description:'FEATURED',
          fuel:'Petrol',
          mile:'5000',
          price:'$750',
          type:'Sport',
          color:'Blue',
          model:'2016',
          img:'https://i.ibb.co/p4xcc8K/product-3.jpg'
     },
     {
          name:'FORD MASTANG', 
          description:'FOR SALE',
          fuel:'Petrol',
          mile:'3000',
          price:'$1250',
          type:'Sport',
          color:'White',
          model:'2020',
          img:'https://i.ibb.co/PDzkcwv/product-1.jpg'
     },
     {
          name:'PORSCHE CAYEN LAST', 
          description:'FOR SALE',
          fuel:'Petrol',
          mile:'1000',
          price:'$1350',
          type:'Sport',
          color:'Black',
          model:'2021',
          img:'https://i.ibb.co/DWG1kkK/product-4.jpg'
     },
     {
          name:'NISSAN', 
          description:'FOR SALE',
          fuel:'Petrol',
          mile:'1000',
          price:'$1550',
          type:'Sport',
          color:'Black',
          model:'2021',
          img:'https://i.ibb.co/1q93XcB/product-7.jpg'
     },
     {
          name:'BMW', 
          description:'FOR SALE',
          fuel:'Petrol',
          mile:'1000',
          price:'$1300',
          type:'Sport',
          color:'Red',
          model:'2020',
          img:'https://i.ibb.co/P5gz4SY/product-8.jpg'
     },
     {
          name:'MAZDA', 
          description:'FOR SALE',
          fuel:'Petrol',
          mile:'2000',
          price:'$2000',
          type:'Sport',
          color:'Red',
          model:'2020',
          img:'https://i.ibb.co/YZ3RWcM/product-9.jpg'
     },
     {
          name:'BMW', 
          description:'FOR SALE',
          fuel:'Petrol',
          mile:'2000',
          price:'$2000',
          type:'Sport',
          color:'Matt Black',
          model:'2020',
          img:'https://i.ibb.co/w69fcwn/product-10.jpg'
     },
     {
          name:'FORD', 
          description:'FOR SALE',
          fuel:'Petrol',
          mile:'2000',
          price:'$1000',
          type:'Sport',
          color:'Black',
          model:'2020',
          img:'https://i.ibb.co/Phj7w6C/product-12.jpg'
     },
     {
          name:'LAMBORGHINI', 
          description:'FOR SALE',
          fuel:'Petrol',
          mile:'4000',
          price:'$1050',
          type:'Sport',
          color:'Red',
          model:'2021',
          img:'https://i.ibb.co/8xHL3hT/product-13.jpg'
     },
     {
          name:'AUDI', 
          description:'FOR SALE',
          fuel:'Petrol',
          mile:'4000',
          price:'$1250',
          type:'Sport',
          color:'Pearl',
          model:'2020',
          img:'https://i.ibb.co/Y05CHjD/product-14.jpg'
     },
     {
          name:'BMW', 
          description:'FOR SALE',
          fuel:'Petrol',
          mile:'4000',
          price:'$1200',
          type:'Sport',
          color:'Orange',
          model:'2020',
          img:'https://i.ibb.co/kJwC4hd/product-15.jpg'
     },
     {
          name:'MASERTI', 
          description:'FOR SALE',
          fuel:'Petrol',
          mile:'4000',
          price:'$1200',
          type:'Sport',
          color:'Matt Black',
          model:'2020',
          img:'https://i.ibb.co/59CqQVg/product-16.jpg'
     },
     {
          name:'TESLA', 
          description:'FOR SALE',
          fuel:'Petrol',
          mile:'4000',
          price:'$1200',
          type:'Sport',
          color:'Matt Black',
          model:'2020',
          img:'https://i.ibb.co/7jXR4p8/product-17.jpg'
     },
     {
          name:'LAMBORGHINI', 
          description:'FOR SALE',
          fuel:'Petrol',
          mile:'4000',
          price:'$1600',
          type:'Sport',
          color:'Red',
          model:'2020',
          img:'https://i.ibb.co/x3w3gF8/product-18.jpg'
     },
     {
          name:'LAMBORGHINI', 
          description:'FOR SALE',
          fuel:'Petrol',
          mile:'4000',
          price:'$1700',
          type:'Sport',
          color:'Red',
          model:'2020',
          img:'https://i.ibb.co/PgXPnVz/product-19.jpg'
     },
     {
          name:'BMW', 
          description:'FOR SALE',
          fuel:'Petrol',
          mile:'4000',
          price:'$2700',
          type:'Sport',
          color:'Pearl',
          model:'2021',
          img:'https://i.ibb.co/DGHPWN4/product-20.png'
     },
     {
          name:'JAGUAR', 
          description:'FOR SALE',
          fuel:'Petrol',
          mile:'4000',
          price:'$2700',
          type:'Sport',
          color:'Dark Red',
          model:'2021',
          img:'https://i.ibb.co/DQ4JKZF/product-22.jpg'
     },
     {
          name:'BENTLY', 
          description:'FOR SALE',
          fuel:'Petrol',
          mile:'4000',
          price:'$2700',
          type:'Sport',
          color:'Black',
          model:'2021',
          img:'https://i.ibb.co/JHfZSZZ/product-23.jpg'
     },
     {
          name:'HYUNDAI', 
          description:'FOR SALE',
          fuel:'Petrol',
          mile:'4000',
          price:'$2700',
          type:'Sport',
          color:'Matt Black',
          model:'2021',
          img:'https://i.ibb.co/C5Rnnyy/product-24.jpg'
     },
     {
          name:'BMW', 
          description:'FOR SALE',
          fuel:'Petrol',
          mile:'4000',
          price:'$2600',
          type:'Sport',
          color:'Black',
          model:'2021',
          img:'https://i.ibb.co/6BQc0mp/product-26.jpg'
     },
    
]